[build]
    command = "npm run generate"
    publish = "dist"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"

# [[redirects]]
#     from = "https://example.netlify.com/*"
#     to = "https://example.com/:splat"
#     status = 301
#     force = true

[[redirects]]
    from = "*"
    to = "/404"
    status = 404
